hotandcold/game/urls.py
"""URL configuration for game app.

The `urlpatterns` list routes URLs to views.
"""

from django.urls import path

from . import views


# URL to view routing.
urlpatterns = [
     # Core views.
    path("", views.home, name="home"),
    path("game/", views.game_list, name="game"),
    path("game/<int:event_id>/", views.game, name="play game"),
    path("game_over/<int:participation_id>/", views.game_over, name="game over"),
    path("leaderboard/", views.leaderboard, name="leaderboard"),

    # Users and authentication.
    path("login/", views.log_in, name="login"),
    path("logout/", views.log_out, name="logout"),
    path("register/", views.register, name="register"),
    path("users/<str:username>/", views.user_details, name="user"),
    path("update_email/", views.update_user_email, name="update user email"),
   
    # Event CRUD operations.
    path("events/", views.list_events, name="list events"),
    path("events/<int:event_id>/", views.event_details, name="event details"),
    path("events/new/", views.create_event, name="create event"),
    path("events/<int:event_id>/update/", views.update_event, name="update event"),
    path("events/<int:event_id>/delete/", views.delete_event, name="delete event"),

    # Treasure chest CRUD operations.
    path("treasure_chests/", views.list_treasure_chests, name="list treasure chests"),
    path("treasure_chests/<int:treasure_chest_id>/", views.treasure_chest_details, name="treasure chest details"),
    path("treasure_chests/new/", views.create_treasure_chest, name="create treasure chest"),
    path("treasure_chests/<int:treasure_chest_id>/update/", views.update_treasure_chest, name="update treasure chest"),
    path("treasure_chests/<int:treasure_chest_id>/delete/", views.delete_treasure_chest, name="delete treasure chest"),
]

hotandcold/hotandcold/urls.py
"""URL configuration for hotandcold project.

The `urlpatterns` list routes URLs to views.

The following list shows the mapping:
    / -> See game.urls.
    /admin -> See admin.site.urls

For more information, see
https://docs.djangoproject.com/en/4.0/topics/http/urls/
"""

from django.contrib import admin
from django.urls import include, path


# URL to view routing.
urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("game.urls")),
]

hotandcold/game/models.py
"""Models used in game app.

Used for creating and storing persistent structured data in the database.
"""

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Player(models.Model):
    """Player model.

    Extends the user model, used to contain game specific information.

    Model attributes:
    user - Actual user that is related to this Player.
    points - Total number of points score.
    is_game_master - Flag to check if this Player is a game master.
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    points = models.IntegerField(default=0)
    is_game_master = models.BooleanField(default=False)


class Event(models.Model):
    """Event model.

    Used for containing locations, start/end times and other information. The
    precision for location data is based on maximum possible precision
    available from Google Maps.

    Model attributes:
    title - Name of Event.
    description - Description of Event.
    start - Datetime of start of Event.
    end - Datetime of end of Event.
    latitude - Latitude of Event location.
    longitude - Longitude of Event location.
    """
    title = models.CharField(max_length=80)
    description = models.CharField(max_length=200)
    start = models.DateTimeField()
    end = models.DateTimeField()
    latitude = models.DecimalField(max_digits=22, decimal_places=16)
    longitude = models.DecimalField(max_digits=22, decimal_places=16)

    def get_status(self):
        """Return a string status of the event.

        The status has one of 3 values:
        "Live" - the event is currently active.
        "Past" - the event happened in the past.
        "Future" - the event will occur in the future.
    
        Arugments:
        self - Event object.
    
        Returns:
        status (str) - status of Event.
        """
        # Get the current date and time.
        current_datetime = timezone.now()

        # Current date is before the start of the Event.
        if current_datetime < self.start:
            return "Future"
        # Current date between start and end of the Event.
        elif self.start <= current_datetime <= self.end:
            return "Live"
        else:
            return "Past"


class Participation(models.Model):
    """Participation model.

    Used for matching Players to Events with a score.

    Model attributes:
    player - Player related to this Participation.
    event - Event
    """
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    score = models.IntegerField(default=0)


class TreasureChest(models.Model):
    """TreasureChest model.

    Used for containing "treasure chests" which contain extra points. The
    precision for location data is based on the maximum possible precision
    available from Google Maps.

    Model attributes:
    name - Name of TreasureChest.
    points - Number of points TreasureChest contains.
    latitude - Latitude of TreasureChest location.
    longitude - Longitude of TreasureChest location.
    """
    name = models.CharField(max_length=80)
    points = models.IntegerField(default=100)
    latitude = models.DecimalField(max_digits=22, decimal_places=16)
    longitude = models.DecimalField(max_digits=22, decimal_places=16)

hotandcold/game/forms.py
"""Forms used in game app.

Used for entering, validating and cleaning user input with HTML forms.
"""

from django import forms
from django.contrib.auth.forms import UserCreationForm


class UserRegistrationForm(UserCreationForm):
    """User registration form.

    Used for creating users. Inherits from UserCreationForm and adds an
    email field.
    """
    class Meta(UserCreationForm.Meta):
        """Metadata for form."""

        # Add email field to form.
        fields = UserCreationForm.Meta.fields + ("email",)


class UserUpdateEmailForm(forms.Form):
    """User update email form.

    Used for updating the email of a user.
    """
    email = forms.EmailField()


class EventCreationForm(forms.Form):
    """Event creation form.

    Used for creating events, inherits from normal Form.
    """
    # Title and description fields.
    title = forms.CharField(label="Title", max_length=80)
    description = forms.CharField(label="Description", max_length=200)

    # Start/end datetime fields.
    start = forms.DateTimeField(label="Start",
            widget=forms.DateTimeInput(attrs={"type": "datetime-local"}))
    end = forms.DateTimeField(label="End",
            widget=forms.DateTimeInput(attrs={"type": "datetime-local"}))

    # Latitude/longitude decimal fields.
    latitude = forms.DecimalField(label="Latitude", max_digits=22, decimal_places=16)
    longitude = forms.DecimalField(label="Longitude", max_digits=22, decimal_places=16)


class TreasureChestCreationForm(forms.Form):
    """TreasureChest creation form.

    Used for creating treasure chests, inherits from normal Form.
    """
    # Name field.
    name = forms.CharField(label="Name")

    # Points field.
    points = forms.IntegerField(label="Points")

    # Latitude/longitude decimal fields.
    latitude = forms.DecimalField(label="Latitude", max_digits=22, decimal_places=16)
    longitude = forms.DecimalField(label="Longitude", max_digits=22, decimal_places=16)

hotandcold/game/views.py
"""Views used in game app.

Handles actual functionality of different views.
"""

from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.shortcuts import redirect, render, get_object_or_404
from django.utils import timezone

from .models import Event, Player, Participation, TreasureChest
from .forms import UserRegistrationForm, UserUpdateEmailForm, \
    EventCreationForm, TreasureChestCreationForm


def home(request):
    """Home view.

    Display the home page.

    Arguments:
    request - Django object containing request information.

    Returns:
    render - Django function to give a HTTP response with a template.
    """
    return render(request, "game/home.html", None)


@login_required(login_url="/login")
def game_list(request):
    """Game list view.

    Shows a list of live games to play.

    Arguments:
    request - Django object containing request information.

    Returns:
    render - Django function to give a HTTP response with a template.
    """
    # Set the title.
    title = "Game List"

    # Get current datetime and list of events which are live.
    current_datetime = timezone.now()
    live_events_list = Event.objects.filter(start__lte=current_datetime,
            end__gte=current_datetime)

    return render(request, "game/game_list.html", {"title": title,
        "live_events_list": live_events_list})


@login_required(login_url="/login")
def game(request, event_id):
    """Game view.

    If the request type is POST and the user is logged in, save the user score
    and redirect the user to the profile page. Otherwise, display the game.

    Arguments:
    request - Django object containing request information.
    event_id - ID of event to use.

    Returns:
    redirect - Django function to redirect the user to another view (profile).
    OR
    render - Django function to give a HTTP response with a template.
    """
    # Set title.
    title = "Game"

    # Check the request type.
    if request.method == "POST":
        # Check if the user is logged in.
        if request.user.is_authenticated:
            # Get the score, event, user and player.
            score = int(request.POST["score"])
            event = get_object_or_404(Event, pk=event_id)
            player = Player.objects.get(user=request.user)

            # Increase the player score. 
            player.points += score
            player.save()

            # Create participation.
            participation = Participation(event=event, player=player, score=score)
            participation.save()

            # Redirect to the profile view.
            return redirect("game over", participation_id=participation.id)

    # Get event and check if event is live.
    event = get_object_or_404(Event, pk=event_id)
    if not event.get_status() == "Live":
        # Event is not live, do not allow user to go further.
        raise PermissionDenied

    # Create list of coordinates from treasure chests.
    treasure_chest_list = [[float(t.latitude), float(t.longitude), t.points] for t in
            TreasureChest.objects.all()]

    # Show the game.
    return render(request, "game/game.html", {"title": title, "event": event,
        "treasure_chest_list": treasure_chest_list})


@login_required(login_url="/login")
def game_over(request, participation_id):
    """Game over view.

    Show the users score at the end of a game.

    Arguments:
    request - Django object containing request information.
    participation_id - ID of participation object to get.

    Returns:
    render - Django function to give a HTTP response with a template.
    """
    # Set title.
    title = "Game Over"

    # Get participation object.
    participation = get_object_or_404(Participation, pk=participation_id)

    # Show game over screen.
    return render(request, "game/game_over.html", {"title": title,
        "participation": participation})


@login_required(login_url="/login")
def leaderboard(request):
    """Leaderboard view.

    Display the top 10 players by total score.

    Arguments:
    request - Django object containing request information.

    Returns:
    render - Django function to give a HTTP response with a template.
    """
    title = "Leaderboard"

    top_players_list = Player.objects.order_by("-points")[:10]
    return render(request, "game/leaderboard.html", {"title": title,
        "top_players_list": top_players_list})


def log_in(request):
    """Login view.

    If the request type is POST, login the user and redirect them to the
    home view. Otherwise, display the user login form.

    Arguments:
    request - Django object containing request information.

    Returns:
    render - Django function to give a HTTP response with a template.
    """
    # Set title.
    title = "Login"

    # Check the request type.
    if request.method == "POST":
        # Create a form with the POST data.
        form = AuthenticationForm(request, data=request.POST)

        # Check form validity.
        if form.is_valid():
            # Get username and password from form.
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")

            # Attempt to authenticate the user.
            user = authenticate(username=username, password=password)
            # Check if the user actually exists.
            if user is not None:
                # Log the user in.
                login(request, user)

                # Redirect to the home view.
                return redirect("home")
        else:
            # Form invalid, show error message.
            messages.warning(request, "Username/password incorrect!")
    
    # Create an empty login form and show it.
    form = AuthenticationForm()
    return render(request, "game/login.html", {"title": title, "form": form})


def log_out(request):
    """Logout the currently logged in user.

    If no one is currently logged in, nothing happens and the user is
    redirected to the home view.

    Arguments:
    request - Django request object containing request information.

    Returns:
    redirect - Django function to redirect user to another view (home).
    """
    logout(request)
    return redirect("home")


def register(request):
    """Account creation/registration view.

    If the request type is POST, register the user, login the user, and
    redirect them to the home page. Otherwise, display the user registration
    form.
    
    Arguments:
    request - Django object containing request information.

    Returns:
    redirect - Django function to redirect the user to another view (home).
    OR
    render - Django function to give a HTTP response with a template.
    """
    # Set title.
    title = "Account Creation"

    # Check the request type.
    if request.method == "POST":
        # Create a form with the POST data.
        form = UserRegistrationForm(request.POST)

        # Check form validity.
        if form.is_valid():
            # Create user and relevant player.
            user = form.save()
            player = Player(user=user)
            player.save()

            # Log the user in.
            login(request, user)
            
            # Redirect to the home view.
            return redirect("home")
        else:
            # Show error messages.
            display_error_messages(request, form)

    # Create an empty registration form and show it.
    form = UserRegistrationForm()
    return render(request, "game/register.html", {"title": title,
        "form": form})


@login_required(login_url="/login")
def user_details(request, username):
    """User details view.

    Show information about a specific user (given by username). Similar to the
    user profile view but does not include links to change details.

    Arguments:
    request - Django object containing request information.
    username (str) - username of user to view.

    Returns:
    render - Django function to give a HTTP response with a template.
    """
    # Get user by username.
    user = get_object_or_404(User, username=username)

    # Set title to include username.
    title = "Profile: " + username

    return render(request, "game/user.html", {"title": title,
        "show_user": user})


@login_required(login_url="/login")
def update_user_email(request):
    """Update user view.

    If the request type is POST and the user is logged in, update the users
    email based on the form data and redirect back to the user profile view.
    Otherwise, display the user update email form.

    Arguments:
    request - Django object containing request information.

    Returns:
    redirect - Django function to redirect the user to another view (profile).
    OR
    render - Django function to give a HTTP response with a template.
    """
    # Set title.
    title = "Update Email"

    # Check the request type.
    if request.method == "POST":
        # Create a form with the POST data and the logged in user.
        form = UserUpdateEmailForm(request.POST)

        # Check form validity.
        if form.is_valid():
            # Get user and email.
            user = request.user
            email = form.cleaned_data.get("email")
            
            # Save the new user details.
            user.email = email
            user.save()

            # Show message of success to user.
            messages.success(request, "User email updated successfully!")

            # Redirect to the profile view.
            return redirect("user", username=user.username)
        else:
            # Show error messages.
            display_error_messages(request, form)

    # Create an empty update form and show it.
    form = UserUpdateEmailForm()

hotandcold/game/templates/game/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Metadata -->
    <title>{{ title }} - dExtination</title>
    
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    
    <meta content="Hot and Cold Group Software Project Game" name="description">
    <meta content="GPS Video Game" name="keywords">
    
    <!-- Favicons -->
    <link href="{% static 'game/img/fireIcon.png' %}" rel="icon">
    <link href="{% static 'game/img/apple-touch-icon.png' %}" rel="apple-touch-icon">
    
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Jost:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
    
    <!-- Vendor CSS Files -->
    <link href="{% static 'game/vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'game/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'game/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'game/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'game/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'game/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'game/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
    
    <!-- Template Main CSS File -->
    <link href="{% static 'game/css/style.css' %}" rel="stylesheet">
  </head>
  <body onload="initialize();">
    <!-- Header -->
    <header id="header" class="fixed-top header-inner-pages">
      <!-- Title -->
      <div class="container d-flex align-items-center">
	<h1 class="logo me-auto"><a href="{% url 'home' %}">dExtination</a></h1>
        
        <!-- Navigation -->
        <nav id="navbar" class="navbar">
          <ul>
            <li><a class="nav-link scrollto" href="{% url 'home' %}">Home</a></li>
	    {% if user.is_authenticated %}
	      {% if user.player.is_game_master %}
	        <li><a class="nav-link scrollto" href="{% url 'list treasure chests' %}">Treasure Chests</a></li>
	      {% endif %}
	      <li><a class="nav-link scrollto" href="{% url 'list events' %}">Events</a></li>
	      <li><a class="nav-link scrollto" href="{% url 'leaderboard' %}">Leaderboard</a></li>
              <li><a class="nav-link scrollto" href="{% url 'user' user.username %}">Profile</a></li>
              <li><a class="nav-link scrollto" href="{% url 'logout' %}">Logout</a></li>
              <li><a class="getstarted scrollto" href="{% url 'game' %}">Game</a></li>
	    {% else %}
	      <li><a class="nav-link scrollto" href="{% url 'register' %}">Account Creation</a></li>
              <li><a class="getstarted scrollto" href="{% url 'login' %}">Login</a></li>
	    {% endif %}
          </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
        </nav>
      </div>
    </header>
    
    <!-- Main -->
    <main id="main">
      <!-- Breadcrumbs -->
      <section id="breadcrumbs" class="breadcrumbs">
        <div class="container">
        <ol>
	  <li><a href="{% url 'home' %}">Home</a></li>
	  <li>{{ title }}</li>
        </ol>
	<h2>{{ title }}</h2>
	<ol>
	  <li>User: {{ user.username|default:"Guest" }}</li>
	</ol>
        </div>
      </section>
   
      <!-- Content -->
      <section class="inner-page">
        <div class="container">
          {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
              {{ message }}
              <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
          {% endfor %}

          {% block content %}{% endblock %}
        </div>
      </section>
    </main>
   
    <!-- Footer -->
    <footer id="footer">
      <div class="container footer-bottom clearfix" style="bottom:0;">
        <div class="copyright">
          &copy; Copyright <strong><span>ExeterGroupSoftwareProject</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
          Inspiration from: <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
      </div>
    </footer>
      
      <div id="preloader"></div>
      <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
      
      <!-- Vendor JS Files -->
      <script src="{% static 'game/vendor/aos/aos.js' %}"></script>
      <script src="{% static 'game/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'game/vendor/glightbox/js/glightbox.min.js' %}"></script>
      <script src="{% static 'game/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
      <script src="{% static 'game/vendor/swiper/swiper-bundle.min.js' %}"></script>
      <script src="{% static 'game/vendor/waypoints/noframework.waypoints.js' %}"></script>
      <script src="{% static 'game/vendor/php-email-form/validate.js' %}"></script>
      
      <!-- Template Main JS File -->
      <script src="{% static 'game/js/main.js' %}"></script>
  </body>
</html>

hotandcold/game/templates/game/event_details.html
{% extends "game/base.html" %}

{% block content %}

<h3>Title: {{ event.title }}</h3>

<p>Description: {{ event.description }}</p>
<p>Start time: <time datetime="{{ event.start|date:'c' }}">{{ event.start }}</time></p>
<p>End time: <time datetime="{{ event.end|date:'c' }}">{{ event.end }}</time></p>
<p>Status: {{ event.get_status }}</p>

{% if user.player.is_game_master or event.get_status == "Past" %}
  <p>Latitude: {{ event.latitude }}</p>
  <p>Longitude: {{ event.longitude }}</p>

  <div id="map_canvas" style="width: auto; height:400px;"></div>
  <br>

  <script src="https://code.jquery.com/jquery-3.5.1.min.js" type="text/javascript"></script>
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDMnC5aWhGCbN-EhosWewAzUyw8T8lVmLs"></script>
  <script type="text/javascript">
  function initialize() {
    // Create map object.
    var map = new google.maps.Map(document.getElementById('map_canvas'), {
      zoom: 16,
      center: new google.maps.LatLng({{ event.latitude }}, {{ event.longitude }}),
      mapTypeId: google.maps.MapTypeId.ROADMAP
    });

    // Create static marker.
    var vMarker = new google.maps.Marker({
      position: new google.maps.LatLng({{ event.latitude }}, {{ event.longitude }}),
      draggable: false
    });

    // Center the map on the markers coordinates.
    map.setCenter(vMarker.position);

    // Add the marker to the map.
    vMarker.setMap(map);
  }
  </script>
{% endif %}

{% if user.player.is_game_master %}
  <p><a href="{% url 'update event' event.id %}">Update Event</a></p>
  <p><a href="{% url 'delete event' event.id %}">Delete Event</a></p>
{% endif %}

<p><a href="{% url 'list events' %}">Back</a></p>

{% endblock %}

hotandcold/game/templates/game/game_list.html
{% extends "game/base.html" %}

{% block content %}

{% if live_events_list %}
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Title</th>
        <th scope="col">Start</th>
        <th scope="col">End</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      {% for event in live_events_list %}
        <tr>
          <td><a href="{% url 'event details' event.id %}">{{ event.title }}</a></td>
          <td>{{ event.start }}</td>
          <td>{{ event.end }}</td>
	  <th scope="row"><a href="{% url 'play game' event.id %}">Go!</a></th>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% else %}
  <p>No Live Events.</p>
{% endif %}

{% endblock %}

hotandcold/game/templates/game/game_over.html
{% extends "game/base.html" %}

{% block content %}

<h3>Score: {{ participation.score }}</h3>

<p><a href="{% url 'event details' participation.event_id %}">Event</a></p>
<p><a href="{% url 'user' user.username %}">Profile</a></p>

{% endblock %}

hotandcold/game/templates/game/list_events.html
{% extends "game/base.html" %}

{% block content %}

{% if user.player.is_game_master %}
  <p><a href="{% url 'create event' %}">New Event</a></p>
{% endif %}

{% if events_list %}
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Title</th>
        <th scope="col">Start</th>
        <th scope="col">End</th>
        <th scope="col">Status</th>
      </tr>
    </thead>
    <tbody>
      {% for event in events_list %}
        <tr>
	  <th scope="row"><a href="{% url 'event details' event.id %}">{{ event.title }}</a></th>
          <td>{{ event.start }}</td>
          <td>{{ event.end }}</td>
          <td>{{ event.get_status }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% else %}
  <p>No Events.</p>
{% endif %}

{% endblock %}

hotandcold/game/templates/game/list_treasure_chests.html
{% extends "game/base.html" %}

{% block content %}

<p><a href="{% url 'create treasure chest' %}">New Treasure Chest</a></p>

{% if treasure_chests_list %}
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Points</th>
      </tr>
    </thead>
    <tbody>
      {% for treasure_chest in treasure_chests_list %}
        <tr>
	  <th scope="row"><a href="{% url 'treasure chest details' treasure_chest.id %}">{{ treasure_chest.name }}</a></th>
          <td>{{ treasure_chest.points }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% else %}
  <p>No Treasure Chests.</p>
{% endif %}

{% endblock %}

hotandcold/game/templates/game/login.html
{% extends "game/base.html" %}

{% block content %}
<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}

  <button type="submit">Log in</button>
</form>
{% endblock %}

hotandcold/game/templates/game/modify_object.html
{% extends "game/base.html" %}

{% block content %}

<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}

  <div id="map_canvas" style="width: auto; height: 400px;"></div>
  <br>

  <button type="submit">{{ modification }} {{ object_name }}</button>
</form>

<script src="https://code.jquery.com/jquery-3.5.1.min.js" type="text/javascript"></script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDMnC5aWhGCbN-EhosWewAzUyw8T8lVmLs"></script>
<script type="text/javascript">
function initialize() {
  // Create map object.
  var map = new google.maps.Map(document.getElementById('map_canvas'), {
    zoom: 16,
    center: new google.maps.LatLng(50.735519, -3.532260),
    mapTypeId: google.maps.MapTypeId.ROADMAP
  });

  // Create a draggable marker on the given coordinates.
  var vMarker = new google.maps.Marker({
    position: new google.maps.LatLng({{ object.latitude|default:50.735519 }}, {{ object.longitude|default:-3.532260 }}),
    draggable: true
  });

  // Add a listener to the marker. The listener gets the coordinates when
  // the drag event ends and updates the input with the new coordinates.
  google.maps.event.addListener(vMarker, 'dragend', function (evt) {
    $("#id_latitude").val(evt.latLng.lat().toFixed(16));
    $("#id_longitude").val(evt.latLng.lng().toFixed(16));
    map.panTo(evt.latLng);
  });

  // Center the map on markers coordinates.
  map.setCenter(vMarker.position);

  // Add the marker to the map.
  vMarker.setMap(map);
}
</script>

{% endblock %}

hotandcold/game/templates/game/profile.html
{% extends "game/base.html" %}

{% block content %}
{% if user.is_authenticated %}
  <p>User: {{ user.username }}</p>
  <p>Email: {{ user.email }}</p>
  {% if user.player.is_game_master %}
    <p>Status: Game master</p>
  {% else %}
    <p>Status: Player</p>
    <p>Points: {{ user.player.points }}</p>
  {% endif %}
{% else %}
  <p>You are not logged in.</p>
{% endif %}
{% endblock %}

hotandcold/game/templates/game/register.html
{% extends "game/base.html" %}

{% block content %}
<form method="POST">
  {% csrf_token %}
  {{ form.as_p}}
  <button type="submit">Submit</button>
</form>
{% endblock %}

hotandcold/game/templates/game/treasure_chest_details.html
{% extends "game/base.html" %}

{% block content %}

<h3>Name: {{ treasure_chest.name }}</h3>

<p>Points: {{ treasure_chest.points }}</p>
<p>Latitude: {{ treasure_chest.latitude }}</p>
<p>Longitude: {{ treasure_chest.longitude }}</p>

<div id="map_canvas" style="width: auto; height:400px;"></div>
<br>

<p><a href="{% url 'update treasure chest' treasure_chest.id %}">Update Treasure Chest</a></p>
<p><a href="{% url 'delete treasure chest' treasure_chest.id %}">Delete Treasure Chest</a></p>

<p><a href="{% url 'list treasure chests' %}">Back</a></p>

<script src="https://code.jquery.com/jquery-3.5.1.min.js" type="text/javascript"></script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDMnC5aWhGCbN-EhosWewAzUyw8T8lVmLs"></script>
<script type="text/javascript">
function initialize() {
  // Create map object.
  var map = new google.maps.Map(document.getElementById('map_canvas'), {
    zoom: 16,
    center: new google.maps.LatLng({{ treasure_chest.latitude }}, {{ treasure_chest.longitude }}),
    mapTypeId: google.maps.MapTypeId.ROADMAP
  });

  // Create static marker.
  var vMarker = new google.maps.Marker({
    position: new google.maps.LatLng({{ treasure_chest.latitude }}, {{ treasure_chest.longitude }}),
		draggable: false
  });

  // Center the map on the markers coordinates.
  map.setCenter(vMarker.position);

  // Add the marker to the map.
  vMarker.setMap(map);
}
</script>

{% endblock %}

hotandcold/game/templates/game/update_user.html
{% extends "game/base.html" %}

{% block content %}

<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}

  <button type="submit">Update</button>
</form>

{% endblock %}